springBootVersion=4.1.1
vaadinVersion=25.2.6
springModulithVersion=2.1.1
dependencyManagementVersion=1.1.7
errorpronePluginVersion=5.1.1
errorproneVersion=2.50.0
nullawayPluginVersion=3.2.0
nullawayVersion=0.14.0
spotbugsPluginVersion=6.5.11
spotbugsVersion=4.10.4
jacocoVersion=0.8.14
sonarqubePluginVersion=7.4.0.8496
gitPropertiesPluginVersion=4.0.1
benManesVersionsPluginVersion=0.61.0
archunitJunit5Version=1.5.0
openrewriteVersion=7.39.0
rewriteRecipeBomVersion=3.36.0
flywayVersion=13.4.0
postgresqlVersion=42.7.13
identityVersion=0.1.0

org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g
org.gradle.configuration-cache=true
