ALTER TABLE user_accounts    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE game_sessions    ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE friendships      ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE user_preferences ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
